source 'https://rubygems.org'

gem 'sqlite3'
gem 'aws-sdk-s3'
gem 'aws-sdk-ssm'
gem 'sinatra'
gem 'apigatewayv2_rack', '>= 0.2.2'
gem 'httpx'
gem 'rexml'
gem 'base64'

group :development do
  gem 'puma'
end
