{
   "jobs": {
      "build": {
         "name": "build (${{ matrix.platform }})",
         "permissions": {
            "contents": "read",
            "id-token": "write"
         },
         "runs-on": "${{ matrix.runner }}",
         "steps": [
            {
               "uses": "docker/setup-buildx-action@v3"
            },
            {
               "uses": "aws-actions/configure-aws-credentials@v4",
               "with": {
                  "aws-region": "ap-northeast-1",
                  "role-skip-session-tagging": true,
                  "role-to-assume": "arn:aws:iam::005216166247:role/GhaDockerPush"
               }
            },
            {
               "id": "login-ecr",
               "uses": "aws-actions/amazon-ecr-login@v2"
            },
            {
               "id": "build-push",
               "uses": "docker/build-push-action@v6",
               "with": {
                  "context": "{{defaultContext}}:freeradius-exporter",
                  "outputs": "type=image,\"name=${{ steps.login-ecr.outputs.registry }}/freeradius-exporter\",push-by-digest=true,name-canonical=true,push=true",
                  "platforms": "${{ matrix.platform }}"
               }
            },
            {
               "env": {
                  "DIGEST": "${{ steps.build-push.outputs.digest }}",
                  "PLATFORM": "${{ matrix.key }}",
                  "RUNNER_TEMP": "${{ runner.temp }}"
               },
               "name": "Export digests",
               "run": "mkdir -p \"${RUNNER_TEMP}/digests\"\nprintenv DIGEST > \"${RUNNER_TEMP}/digests/${PLATFORM}\"\n"
            },
            {
               "name": "Upload digests",
               "uses": "actions/upload-artifact@v4",
               "with": {
                  "if-no-files-found": "error",
                  "name": "digests-${{ matrix.key }}",
                  "path": "${{ runner.temp }}/digests/*",
                  "retention-days": 1
               }
            }
         ],
         "strategy": {
            "matrix": {
               "include": [
                  {
                     "key": "linux-arm64",
                     "platform": "linux/arm64",
                     "runner": "ubuntu-24.04-arm"
                  }
               ]
            }
         }
      },
      "merge": {
         "needs": [
            "build"
         ],
         "permissions": {
            "id-token": "write"
         },
         "runs-on": "ubuntu-latest",
         "steps": [
            {
               "uses": "docker/setup-buildx-action@v3"
            },
            {
               "uses": "aws-actions/configure-aws-credentials@v4",
               "with": {
                  "aws-region": "ap-northeast-1",
                  "role-skip-session-tagging": true,
                  "role-to-assume": "arn:aws:iam::005216166247:role/GhaDockerPush"
               }
            },
            {
               "id": "login-ecr",
               "uses": "aws-actions/amazon-ecr-login@v2"
            },
            {
               "name": "Download digests",
               "uses": "actions/download-artifact@v4",
               "with": {
                  "merge-multiple": true,
                  "path": "${{ runner.temp }}/digests",
                  "pattern": "digests-*"
               }
            },
            {
               "env": {
                  "REPO": "${{ steps.login-ecr.outputs.registry }}/freeradius-exporter",
                  "RUNNER_TEMP": "${{ runner.temp }}",
                  "SHA": "${{ github.sha }}"
               },
               "name": "Push manifest",
               "run": "cat \"${RUNNER_TEMP}\"/digests/* | xargs -I{} printf \"%s@%s\" \"${REPO}\" {} | docker buildx imagetools create -f /dev/stdin -t \"${REPO}:latest\" -t \"${REPO}:${SHA}\"\ndocker buildx imagetools inspect \"${REPO}:${SHA}\"\n"
            }
         ]
      }
   },
   "name": "docker-freeradius-exporter",
   "on": {
      "push": {
         "branches": [
            "main",
            "test"
         ],
         "paths": [
            "freeradius-exporter/**",
            ".github/workflows/docker-freeradius-exporter.yml"
         ]
      }
   }
}
