{
   "jobs": {
      "build": {
         "name": "build",
         "permissions": {
            "contents": "read",
            "id-token": "write"
         },
         "runs-on": "ubuntu-latest",
         "steps": [
            {
               "uses": "docker/setup-qemu-action@v2"
            },
            {
               "uses": "docker/setup-buildx-action@v2"
            },
            {
               "uses": "aws-actions/configure-aws-credentials@v1",
               "with": {
                  "aws-region": "us-west-2",
                  "role-skip-session-tagging": true,
                  "role-to-assume": "arn:aws:iam::005216166247:role/GhaDockerPush"
               }
            },
            {
               "id": "login-ecr",
               "uses": "aws-actions/amazon-ecr-login@v1"
            },
            {
               "uses": "docker/build-push-action@v3",
               "with": {
                  "context": "{{defaultContext}}:attendee-gate",
                  "platforms": "linux/arm64",
                  "push": true,
                  "tags": "${{ steps.login-ecr.outputs.registry }}/attendee-gate:${{ github.sha }},${{ steps.login-ecr.outputs.registry }}/attendee-gate:latest"
               }
            }
         ]
      }
   },
   "name": "docker-attendee-gate",
   "on": {
      "push": {
         "branches": [
            "main",
            "test"
         ],
         "paths": [
            "attendee-gate/**",
            ".github/workflows/docker-attendee-gate.yml"
         ]
      }
   }
}
